# Generated by Django 5.2.6 on 2026-01-26 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0009_patient_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('species', models.CharField(default='cat', max_length=50)),
                ('schedule_mode', models.CharField(choices=[('interval', 'Interval'), ('series', 'Series')], default='interval', max_length=20)),
                ('interval_days', models.IntegerField(blank=True, null=True)),
                ('grace_days', models.IntegerField(default=0)),
                ('series_doses', models.IntegerField(blank=True, null=True)),
                ('series_min_age_days', models.IntegerField(blank=True, null=True)),
                ('series_gap_days', models.IntegerField(blank=True, null=True)),
                ('booster_interval_days', models.IntegerField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.PositiveIntegerField()),
                ('dose_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('clinic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='patients.patient')),
                ('vaccine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='vaccinations.vaccinetype')),
            ],
        ),
    ]
