# Generated by Django 5.2.6 on 2026-01-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinedose',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
