# Generated by Django 5.2.6 on 2026-02-04 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('vaccinations', '0003_remove_vaccinetype_schedule_mode_series_booster'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinedose',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccine_doses', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='vaccinedose',
            name='veterinarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccine_doses', to='clinics.veterinarian'),
        ),
    ]
