# Generated by Django 5.2.6 on 2026-02-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0004_vaccinedose_clinic_vaccinedose_veterinarian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinedose',
            name='clinic_name',
        ),
    ]
