# Generated by Django 5.2.6

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0005_remove_vaccinedose_clinic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinedose',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='vaccinedose',
            name='manufacturer',
        ),
    ]
