# Generated by Django 5.2.6 on 2026-02-04 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0006_remove_vaccinedose_product_name_and_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vaccinations.vaccinetype')),
            ],
        ),
        migrations.AddField(
            model_name='vaccinedose',
            name='vaccine_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccine_doses', to='vaccinations.vaccineproduct'),
        ),
    ]
