# Generated by Django 5.2.6

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0007_vaccineproduct_vaccinedose_vaccine_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinedose',
            name='dose_number',
        ),
    ]
