when:
  - event: push
    branch: main
steps:
  - name: build-and-push-api
    image: woodpeckerci/plugin-docker-buildx:6
    privileged: true
    settings:
      context: ./api
      dockerfile: Dockerfile
      platforms: linux/arm64
      repo: wswsws/api
      registry: registry.benjiao.net
      tags:
        - latest
        - ${WOODPECKER_COMMIT_SHA}
