services:
  api:
    build: api/
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "${WSWSWS_API_PORT}:8000"
    depends_on:
      - db
      - redis
    environment:
      WSWSWS_POSTGRES_DB: ${WSWSWS_POSTGRES_DB}
      WSWSWS_POSTGRES_DB_TEST: ${WSWSWS_POSTGRES_DB_TEST}
      WSWSWS_POSTGRES_HOST: ${WSWSWS_POSTGRES_HOST}
      WSWSWS_POSTGRES_PORT: ${WSWSWS_POSTGRES_PORT}
      WSWSWS_POSTGRES_USER: ${WSWSWS_POSTGRES_USER}
      WSWSWS_POSTGRES_PASSWORD: ${WSWSWS_POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG} 
      WSWSWS_ALLOWED_HOSTS: ${WSWSWS_ALLOWED_HOSTS}
      WSWSWS_TIMEZONE: ${WSWSWS_TIMEZONE}
    restart: unless-stopped
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${WSWSWS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${WSWSWS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${WSWSWS_POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  migrate:
    build: api/
    command: python manage.py migrate --noinput
    depends_on:
      - db
      - api
    environment:
      WSWSWS_POSTGRES_DB: ${WSWSWS_POSTGRES_DB}
      WSWSWS_POSTGRES_USER: ${WSWSWS_POSTGRES_USER}
      WSWSWS_POSTGRES_PASSWORD: ${WSWSWS_POSTGRES_PASSWORD}
      WSWSWS_POSTGRES_HOST: ${WSWSWS_POSTGRES_HOST}
      WSWSWS_POSTGRES_PORT: ${WSWSWS_POSTGRES_PORT}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}

  redis:
    image: redis:latest
    restart: unless-stopped

  celery-worker:
    build: api/
    command: celery -A api worker --loglevel=info --concurrency=1
    depends_on:
      - redis
      - db
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      WSWSWS_POSTGRES_DB: ${WSWSWS_POSTGRES_DB}
      WSWSWS_POSTGRES_USER: ${WSWSWS_POSTGRES_USER}
      WSWSWS_POSTGRES_PASSWORD: ${WSWSWS_POSTGRES_PASSWORD}
      WSWSWS_POSTGRES_HOST: ${WSWSWS_POSTGRES_HOST}
      WSWSWS_POSTGRES_PORT: ${WSWSWS_POSTGRES_PORT}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
    restart: unless-stopped

  celery-beat:
    build: api/
    command: celery -A api beat --loglevel=info
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      WSWSWS_POSTGRES_DB: ${WSWSWS_POSTGRES_DB}
      WSWSWS_POSTGRES_USER: ${WSWSWS_POSTGRES_USER}
      WSWSWS_POSTGRES_PASSWORD: ${WSWSWS_POSTGRES_PASSWORD}
      WSWSWS_POSTGRES_HOST: ${WSWSWS_POSTGRES_HOST}
      WSWSWS_POSTGRES_PORT: ${WSWSWS_POSTGRES_PORT}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
    restart: unless-stopped

volumes:
  postgres_data:

