# Generated by Django 5.2.6 on 2026-04-04 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_make_notes_details_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='healthcondition',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='notes',
        ),
    ]
