# Generated by Django 5.2.6 on 2026-04-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_remove_diagnosis_notes_remove_followup_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='follow_up_datetime',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='record_datetime',
        ),
        migrations.AddField(
            model_name='followup',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
