# Generated by Django 5.2.6 on 2026-04-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_remove_followup_follow_up_datetime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
