# Generated by Django 5.2.6 on 2025-09-28 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('frequency', models.IntegerField()),
                ('interval', models.CharField(max_length=100)),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_schedules', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('given', 'Given'), ('skipped', 'Skipped')], max_length=10)),
                ('treatment_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='treatments.treatmentschedule')),
            ],
        ),
    ]
