# Generated by Django 5.2.6 on 2025-09-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentschedule',
            name='dosage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentschedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentschedule',
            name='frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentschedule',
            name='interval',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentschedule',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='treatmentschedule',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentschedule',
            name='unit',
            field=models.CharField(blank=True, default='mL', max_length=50, null=True),
        ),
    ]
