# Generated by Django 5.2.6 on 2025-09-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_alter_treatmentschedule_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentschedule',
            name='interval',
            field=models.IntegerField(blank=True, choices=[(1, 'DAILY'), (2, 'EVERY OTHER DAY')], null=True),
        ),
    ]
