# Generated by Django 5.2.6 on 2025-09-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0003_alter_treatmentschedule_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentschedule',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
