# Generated by Django 5.2.6 on 2025-09-28 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('treatments', '0004_alter_treatmentschedule_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentschedule',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_schedules', to='inventory.medicine'),
        ),
    ]
