# Generated by Django 5.2.6 on 2025-09-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0005_treatmentschedule_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentinstance',
            old_name='datetime',
            new_name='scheduled_time',
        ),
    ]
