# Generated by Django 5.2.6 on 2025-09-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0006_rename_datetime_treatmentinstance_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentinstance',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Given'), (3, 'Skipped')]),
        ),
    ]
