# Generated by Django 5.2.6 on 2025-09-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0007_alter_treatmentinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentinstance',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Given'), (3, 'Skipped')], default=1),
        ),
    ]
