# Generated by Django 5.2.6 on 2025-09-30 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0008_alter_treatmentinstance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.IntegerField(choices=[(1, 'Morning'), (2, 'Noon'), (3, 'Afternoon'), (4, 'Evening')])),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField(default='08:00')),
                ('end_time', models.TimeField(default='12:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('session_type', 'session_date')},
            },
        ),
        migrations.AddField(
            model_name='treatmentinstance',
            name='treatment_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='treatments.treatmentsession'),
        ),
    ]
