# Generated by Django 5.2.6 on 2025-09-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0009_treatmentsession_treatmentinstance_treatment_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentsession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='treatmentsession',
            name='start_time',
        ),
    ]
