# Generated by Django 5.2.6 on 2026-01-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0010_remove_treatmentsession_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentschedule',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='treatmentschedule',
            name='start_date',
        ),
        migrations.AddField(
            model_name='treatmentschedule',
            name='doses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentschedule',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
