# Generated by Django 5.2.6 on 2026-04-05 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_remove_diagnosis_notes_remove_followup_notes_and_more'),
        ('treatments', '0012_treatmentschedule_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentschedule',
            name='health_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_schedules', to='medical.healthcondition'),
        ),
        migrations.AddField(
            model_name='treatmentschedule',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_schedules', to='medical.medicalrecord'),
        ),
    ]
