# Generated by Django 5.2.6 on 2026-06-24 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0013_treatmentschedule_health_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Schedule Batches',
            },
        ),
        migrations.AddField(
            model_name='treatmentschedule',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='treatments.schedulebatch'),
        ),
    ]
