# Generated by Django 5.2.6 on 2025-10-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_birth_date_alter_patient_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='spay_netuer_clinic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='spay_neuter_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='spay_neuter_status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
