# Generated by Django 5.2.6 on 2025-10-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_spay_netuer_clinic_patient_spay_neuter_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='spay_netuer_clinic',
            new_name='spay_neuter_clinic',
        ),
    ]
