# Generated by Django 5.2.6 on 2026-01-26 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_seed_patientstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patientstatus'),
        ),
    ]
