# Generated by Django 5.2.6 on 2026-01-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstatus',
            name='is_in_care',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
