# Generated by Django 5.2.6 on 2025-10-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='color',
            field=models.CharField(blank=True, default='#FFA500', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
